### ISSUE TITLE
System disconnects constantly after installing Python extension

### ISSUE THREAD

**Issue by davystrong** [vhqtvn/vscode-android-server#2]
I installed the Python extension and since then it always gives me the error "Cannot reconnect. Please reload the window" a few seconds after VSCode appearing on my screen. Any idea what has gone wrong?

**Comment by vhqtvn** [comment]
Sorry for late reply, I dont expect to see issue in this repo.
Have you tried to reset file system?

**Comment by davystrong** [comment]
No problem, I'm not actually needing this right now. Yes, I reset the file system and it once again worked, until I installed the python extension again.

**Comment by vhqtvn** [comment]
Please try again on latest version, maybe it can work now.

**Comment by vhqtvn** [comment]
Hmm no it still error, i'm checking.

**Comment by vhqtvn** [comment]
You should open the terminal and install python first by running `pkg install python`

**Comment by davystrong** [comment]
Ok, I'll give that a try, though I thought I had already done that.

**Comment by davystrong** [comment]
No, unfortunately it still crashes. I reloaded after installing the extension and it crashed soon afterwards, but when I clicked reload it worked perfectly. However, after restarting the app, the problem started again and is constant. Quick question, the Termux "intance" this runs in isn't the same as that of the Termux app right? Just wondering if something I had setup is causing it.
